# ==============================================
# 🚀 CONFIGURACIÓN DE RENDER
# ==============================================
# Este archivo define la infraestructura en Render

services:
  # ==============================================
  # 🎯 SERVICIO WEB (Backend NestJS)
  # ==============================================
  - type: web
    name: nikra-backend
    env: node
    region: frankfurt  # Frankfurt (Alemania) - Única región europea, óptima para España
    plan: starter  # Cambia a standard o professional según necesites
    branch: main  # Rama de Git que se desplegará
    buildCommand: npm install --include=dev && npx nest build
    startCommand: npm run start:prod
    healthCheckPath: /api/docs
    
    # Variables de entorno
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: PORT
        value: 3000
      
      # Base de datos (vinculada al servicio de PostgreSQL abajo)
      - key: DB_HOST
        fromDatabase:
          name: nikra-db
          property: host
      
      - key: DB_PORT
        fromDatabase:
          name: nikra-db
          property: port
      
      - key: DB_USERNAME
        fromDatabase:
          name: nikra-db
          property: user
      
      - key: DB_PASSWORD
        fromDatabase:
          name: nikra-db
          property: password
      
      - key: DB_DATABASE
        fromDatabase:
          name: nikra-db
          property: database
      
      # JWT Secrets (IMPORTANTE: Secret estático para consistencia)
      - key: JWT_SECRET
        value: nikra-jwt-secret-2025-production-secure-key-xyz789
      
      - key: JWT_EXPIRES_IN
        value: 24h
      
      - key: JWT_REFRESH_SECRET
        value: nikra-refresh-secret-2025-production-secure-key-abc123
      
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      
      # CORS - Orígenes permitidos (separados por comas)
      - key: ALLOWED_ORIGINS
        value: https://ccaceuta.com,https://www.ccaceuta.com,https://nikra-front.vercel.app,https://nikra-backend.onrender.com,https://sorteos.centrocomercialabiertodeceuta.es,http://localhost:3000,http://localhost:4200
    
    # Disco persistente para archivos subidos
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 10

# ==============================================
# 🗄️ BASE DE DATOS POSTGRESQL
# ==============================================
databases:
  - name: nikra-db
    databaseName: nikra_db
    user: nikra_user
    # Sin especificar 'plan' - Render usará el plan por defecto disponible
    region: frankfurt  # Frankfurt - IMPORTANTE: Debe ser la misma región que el servicio web
    ipAllowList: []  # Vacío = accesible solo desde servicios de Render

