#!/bin/bash
# ==============================================
# 🔍 VERIFICAR ESTADO DEL DISCO PERSISTENTE
# ==============================================

echo "🔍 Verificando estado del disco persistente en Render..."
echo ""
echo "📋 Comandos para ejecutar en el Shell de Render:"
echo ""
echo "1️⃣ Verificar que el directorio /app/uploads existe:"
echo "   ls -la /app/"
echo ""
echo "2️⃣ Verificar el contenido del directorio uploads:"
echo "   ls -la /app/uploads/"
echo ""
echo "3️⃣ Verificar subdirectorios (avatars, campaigns, associates):"
echo "   ls -la /app/uploads/avatars/"
echo "   ls -la /app/uploads/campaigns/"
echo "   ls -la /app/uploads/associates/"
echo ""
echo "4️⃣ Verificar uso de espacio en disco:"
echo "   df -h /app/uploads"
echo ""
echo "5️⃣ Verificar permisos:"
echo "   stat /app/uploads"
echo ""
echo "6️⃣ Ver si hay archivos ocultos:"
echo "   find /app/uploads -type f -name '.*' -ls"
echo ""
echo "7️⃣ Ver tamaño total de archivos:"
echo "   du -sh /app/uploads/*"
echo ""
echo "8️⃣ Ver logs de la aplicación para verificar uploads:"
echo "   (revisar en la pestaña 'Logs' del dashboard de Render)"
echo ""
echo "===================================================="
echo "✅ Ejecuta estos comandos en el Shell de Render para diagnosticar el problema"
echo "===================================================="

